# Generated by Django 3.1.7 on 2021-04-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.IntegerField()),
                ('flight_id', models.IntegerField()),
                ('fare_condition', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
